### ISSUE TITLE
Alerts absent from Children's Health Defense pages

### ISSUE THREAD

**Issue by grahamperrin** [jacobb84/fact-layer#2]
In screenshots below: 

* https://www.naturalnews.com/2018-06-08-the-criminalization-of-science-whistleblowers-a-mind-blowing-interview-with-judy-mikovits-phd.html to the left
* https://childrenshealthdefense.org/news/plague-of-corruption-book-the-talented-dr-judy-mikovits/ to the right. 

Respective descriptions of quackery: 

* https://mediabiasfactcheck.com/natural-news/
* https://mediabiasfactcheck.com/childrens-health-defense/

Chromium 83.0.4103.116 (Official Build) (64-bit): 

![image](https://user-images.githubusercontent.com/192271/87873024-cfc0bd00-c9b5-11ea-8c25-9a407e78049d.png)

Firefox 78.0.2: 

![image](https://user-images.githubusercontent.com/192271/87872956-24176d00-c9b5-11ea-9e37-0835edd6f4d0.png)

Neither browser presents an alert for Children's Health Defense. 

### Comparison

The conspiracy-pseudoscience alert is similarly absent with the [Official Media Bias Fact Check Icon](https://mediabiasfactcheck.com/appsextensions/). 

Yellow **CP** icon visible in both screenshots, to the left but not to the right …

**Comment by grahamperrin** [comment]
https://twitter.com/grahamperrin/status/1284805762867515392 addresses `@MBFC_News`

**Comment by jacobb84** [comment]
Hi @grahamperrin, thank you for the detailed bug report! The websites database was fairly out of date because I haven't had much time lately to devote to the project, but I pushed up an update that will fix this (the data structure of the websites database had changed a little, so you'll need to update the plugin itself before it will pull down the update). Firefox already has the update available, and chrome will as soon as they review it.

**Comment by grahamperrin** [comment]
Thanks! A surprise, I half-expected the cause of the issue to be elsewhere, given the comparable absence of the MBFC icon. Didn't want to be wasting your time. 

Re: https://addons.mozilla.org/addon/media-bias-fact-check-icon/ should I now also report the issue (via e-mail) to Jeffrey Carl Faden?

**Comment by grahamperrin** [comment]
Fix confirmed in Firefox. 

----

Members of the Cult of Judy are gonna _love_ stuff like this ;-)

![image](https://user-images.githubusercontent.com/192271/87908477-57fa9d00-ca5e-11ea-82f9-35c375c427e0.png)

**Comment by jacobb84** [comment]
Hah, I'm sure they will ;-) Looks like Chrome has approved it as well so I'll close the ticket. Concerning MBFC icon, it couldn't hurt. Looks like he has a github page as well though, so maybe you could open a ticket there: https://github.com/JeffreyATW/mbfc_icon 
Last update was around 10 months ago, so I wouldn't be surprised if his is just out of date like mine was.
